---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-app-2
  namespace: default
spec:
  chart:
    spec:
      chart: node-app
      version: 0.3.0
      sourceRef:
        kind: HelmRepository
        name: mycharts
        namespace: default
  interval: 1m0s

